    -- Seed data for `story_sessions`: none, for the moment.
    --
    -- The only sittings ever seeded were the three recorded ones of An Eastern
    -- King, a story of the storyteller@irun.games account. That account is
    -- made by signing in and no seed creates it, so the stories it owned were
    -- taken out of db/seeds/seed_stories.sql and their sittings went with
    -- them. None of the example stories that remain records a sitting, so this
    -- seed inserts nothing; the file stays as the place the table is seeded
    -- from when it has something to seed.
