    -- Seed data for `story_scenes`: none, for the moment.
    --
    -- The only scenes ever seeded were the twenty-one of An Eastern King, a
    -- story of the storyteller@irun.games account. That account is made by
    -- signing in and no seed creates it, so the stories it owned were taken
    -- out of db/seeds/seed_stories.sql, and the sittings and the scenes that
    -- hung off them went with them. None of the example stories that remain
    -- has scenes, so this seed inserts nothing; the file stays as the place
    -- the table is seeded from when it has something to seed.
