-- migrate:up
-- A player's presence at a story's sessions: waiting for the table to open,
-- at it, gone quiet, or gone. The player is id_created_by_user, which the
-- metatable procedures add along with created_at / updated_at, so no user
-- column is declared here. updated_at doubles as the heartbeat: the page a
-- player has open touches the row every few seconds, and set_updated_at
-- stamps it.
--
-- id_story_session is null while the player waits, because a player waits
-- precisely when the story has no session being played, and there may be no
-- session row at all to point at. When a session opens, the waiting row is
-- attached to it and moves to PRESENT. id_story is always set, so a waiting
-- row still knows whose room it is in.
--
-- Its status runs through the session players workflow seeded in
-- seeds/seed_s_statuses.sql (WAITING, PRESENT, AWAY, LEFT; WAITING is the
-- default), and the workflow procedures add the CHECK on status, the
-- waiting_at / present_at / away_at / left_at columns, the trigger that
-- stamps each as the row enters that status, and the trigger that rejects a
-- transition the workflow does not list. waiting_at is what the waiting
-- room's clock counts from: a player coming back from away or from leaving
-- re-enters WAITING, which restamps it.
--
-- Nothing here holds id_story_session to id_story's sessions; the action
-- that attaches a row takes the session from the story's own pointer.
--
-- Both foreign keys cascade: presence means nothing once the story or the
-- session is gone.
CREATE TABLE IF NOT EXISTS session_players (
    id_session_player integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_story          integer NOT NULL REFERENCES stories (id_story) ON DELETE CASCADE,
    id_story_session  integer REFERENCES story_sessions (id_story_session) ON DELETE CASCADE,
    status            varchar NOT NULL DEFAULT 'WAITING'
);

-- The whole _tables setup in one call: registration, the needs_* flags, the
-- audit columns and their foreign keys, activity_log, the status workflow,
-- and the foreign-key indexes. It raises if the table is missing from
-- _tables afterwards, or if workflow -6 is unseeded.
CALL _p_set_and_update_table_features('session_players',
    p_timestamps          := TRUE,
    p_user_ids            := TRUE,
    p_activity_log        := TRUE,
    p_status_workflow_ids := ARRAY[-6]);

-- One row per player per session, and one waiting row per player per story,
-- so the heartbeat can upsert either. Two partial indexes rather than one
-- constraint, because a UNIQUE over a nullable id_story_session would let
-- any number of waiting rows through: nulls are distinct. They can only be
-- built once the procedure above has made id_created_by_user.
CREATE UNIQUE INDEX IF NOT EXISTS session_players_id_story_session_player_key
    ON session_players (id_story_session, id_created_by_user)
    WHERE id_story_session IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS session_players_waiting_player_key
    ON session_players (id_story, id_created_by_user)
    WHERE id_story_session IS NULL;

-- migrate:down

