-- migrate:up
-- An element brought into a scene: one row per element per scene, so a scene
-- can call on the story's people, places and things, and an element can turn
-- up in any number of scenes.
--
-- Its status runs through the scene elements workflow seeded in
-- seeds/seed_s_statuses.sql (INVISIBLE, READY and DISABLED, each of which may
-- move to either of the others; READY is the default), and the workflow
-- procedures add the CHECK on status, the invisible_at / ready_at /
-- disabled_at columns, the trigger that stamps them and the trigger that
-- rejects any transition the workflow does not list. The element's own status
-- is a separate thing: this one is how it stands in this scene.
--
-- activity_log is on as it is for every workflow table: the transition
-- trigger appends each move to it, and warns on every move when it is missing.
--
-- Who linked the element is id_created_by_user, which the metatable
-- procedures add along with created_at / updated_at, so no user column is
-- declared here.
--
-- Both foreign keys cascade: a link means nothing once its scene or its
-- element is gone. Nothing here holds the scene and the element to the same
-- story; the server action that links them checks it, as it checks the
-- caller owns the story.
CREATE TABLE IF NOT EXISTS scene_elements (
    id_scene_element integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_story_scene   integer NOT NULL REFERENCES story_scenes (id_story_scene) ON DELETE CASCADE,
    id_element       integer NOT NULL REFERENCES elements (id_element) ON DELETE CASCADE,
    status           varchar NOT NULL DEFAULT 'READY',
    -- An element is in a scene once; its status says how.
    CONSTRAINT scene_elements_id_story_scene_id_element_key UNIQUE (id_story_scene, id_element)
);

-- The whole _tables setup in one call: registration, the needs_* flags, the
-- audit columns and their foreign keys, activity_log, the status workflow,
-- and the foreign-key indexes. It raises if the table is missing from
-- _tables afterwards, or if workflow -5 is unseeded.
CALL _p_set_and_update_table_features('scene_elements',
    p_timestamps          := TRUE,
    p_user_ids            := TRUE,
    p_activity_log        := TRUE,
    p_status_workflow_ids := ARRAY[-5]);

-- migrate:down

