-- migrate:up
-- A scene of a story: a card in the Scenes column of the Prep Work board,
-- written ahead of play and then run at the table. Its status runs through
-- the story_scenes workflow seeded in seeds/seed_s_statuses.sql (pending,
-- active and complete, each of which may move to either of the others;
-- pending is the default), and the workflow procedures below add everything
-- that enforces it: the CHECK on status, the pending_at / active_at /
-- complete_at columns, the trigger that stamps each one when the row enters
-- that status, and the trigger that rejects any transition the workflow does
-- not list. Every transition is also appended to activity_log, which the
-- transition trigger expects to find on the table.
--
-- The storyteller who wrote the scene is id_created_by_user, which the
-- metatable procedures add along with created_at / updated_at, so no user
-- column is declared here.
--
-- A scene belongs to its story from the moment it is prepped, so id_story is
-- NOT NULL; the session is the sitting it was actually played in, which it
-- does not have while it waits on the board, so id_story_session is nullable
-- and survives the session being deleted.
CREATE TABLE IF NOT EXISTS story_scenes (
    id_story_scene    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_story          integer NOT NULL REFERENCES stories (id_story) ON DELETE CASCADE,
    id_story_session  integer REFERENCES story_sessions (id_story_session) ON DELETE SET NULL,
    status            varchar NOT NULL DEFAULT 'PENDING',
    scene_title       text    NOT NULL,
    scene_description text
);

-- Register the table so the needs_* flags have a row to land on. On a
-- database built from scratch _tables may be empty at this point.
CALL _p_update_tables();

-- _p_update_tables() only overwrites the has_* flags on conflict, never the
-- needs_* ones, the workflow mapping or the search fields, so this survives
-- later runs. -2 is the Story Scenes Status Workflow in
-- seeds/seed_s_status_workflows.sql. search_text joins status, scene_title
-- and scene_description, so a scene is found by what it is called, what it
-- says, or where it has got to.
UPDATE _tables
SET needs_timestamps      = TRUE,
    needs_user_ids        = TRUE,
    needs_activity_log    = TRUE,
    s_status_workflow_ids = ARRAY[-2],
    search_fields         = ARRAY ['status', 'scene_title', 'scene_description'],
    search_field_name     = 'search_text',
    updated_at            = NOW()
WHERE table_name = 'story_scenes';

-- A table absent from _tables would silently miss out, and a workflow that
-- has not been seeded would leave status unguarded, so say so instead.
DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM _tables WHERE table_name = 'story_scenes') THEN
            RAISE EXCEPTION
                'story_scenes is not present in _tables even after '
                    '_p_update_tables(), so its audit columns cannot be added.';
        END IF;
        IF NOT EXISTS (SELECT 1 FROM s_status_workflows WHERE s_status_workflow_id = -2) THEN
            RAISE EXCEPTION
                'Workflow -2 is not present in s_status_workflows; run the '
                    'seed_s_status_workflows and seed_s_statuses migrations first.';
        END IF;
    END
$$;

-- Adds created_at / updated_at with the set_updated_at trigger, then
-- id_created_by_user / id_updated_by_user with their foreign keys, then
-- activity_log. All three are idempotent across every flagged table.
CALL _p_update_tables_timestamps();
CALL _p_update_tables_user_ids();
CALL _p_update_tables_activity_log();

-- Build the workflow onto the table: the CHECK constraint on status, the
-- pending_at / active_at / complete_at columns, the BEFORE INSERT OR UPDATE
-- trigger that stamps them, and the BEFORE UPDATE trigger that validates a
-- transition against s_statuses. _p_attach_workflow_triggers does nothing
-- while the workflow has no workflow_trigger, and is here so a later one is
-- picked up by a re-run.
CALL _p_update_workflow_constraints();
CALL _p_update_workflow_columns();
CALL _p_update_workflow_status_timestamp_triggers();
CALL _p_attach_workflow_triggers();
CALL _p_attach_status_transition_triggers();

-- Build search_text from the fields registered above. The procedure skips a
-- table whose search column already exists, so a re-run leaves it alone; to
-- rebuild it, drop the column first.
CALL _p_update_tables_search_fields();

-- The procedure logs rather than raises when it cannot build the column, so
-- check that it did.
DO
$$
    BEGIN
        IF NOT _column_exists('story_scenes', 'search_text') THEN
            RAISE EXCEPTION 'story_scenes.search_text was not created by _p_update_tables_search_fields().';
        END IF;
    END
$$;

-- A picture for the scene: the same kind of link story_sessions keeps, an
-- address rather than an upload. Added with ALTER rather than in the CREATE
-- TABLE above so a database built before the column existed gains it on the
-- next run, the way story_sessions gained paused_time.
ALTER TABLE story_scenes
    ADD COLUMN IF NOT EXISTS image_link text;

COMMENT ON COLUMN story_scenes.image_link IS
    'Address of a picture for the scene, shown in its info panel. Not part of '
    'search_text: a URL is not something anyone searches a board for.';

-- Both foreign keys are looked up rather than joined one row at a time — the
-- board reads every scene of a story, the session view every scene of a
-- sitting — so back them with indexes. Same names _p_update_fk_indexes would
-- choose, so its next run finds them already in place.
CREATE INDEX IF NOT EXISTS idx_fk_story_scenes_id_story ON story_scenes (id_story);
CREATE INDEX IF NOT EXISTS idx_fk_story_scenes_id_story_session ON story_scenes (id_story_session);

-- migrate:down

