-- migrate:up
-- One row per user holding every key/value preference the web app keeps for
-- them, as a single jsonb object. id_user is the lookup and upsert key, which
-- is why it exists alongside the id_created_by_user the metatable adds below:
-- the two carry the same user, but a UNIQUE constraint has to sit on a column
-- this file owns, not on one a procedure adds later. The CHECK keeps the
-- column an object because the app writes to it with `||`, which merges two
-- objects and would silently do something else with an array or a scalar.
CREATE TABLE IF NOT EXISTS user_preferences (
    id_user_preference integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user            uuid  NOT NULL UNIQUE REFERENCES users (id_user),
    preferences        jsonb NOT NULL DEFAULT '{}'::jsonb
        CONSTRAINT user_preferences_is_object CHECK (jsonb_typeof(preferences) = 'object')
);

-- Register the table so the needs_* flags have a row to land on. On a
-- database built from scratch _tables may be empty at this point.
CALL _p_update_tables();

-- _p_update_tables() only overwrites the has_* flags on conflict, never the
-- needs_* ones, so this survives later runs.
UPDATE _tables
SET needs_timestamps = TRUE,
    needs_user_ids   = TRUE,
    updated_at       = NOW()
WHERE table_name = 'user_preferences';

-- A table absent from _tables would silently miss out, so say so instead.
DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM _tables WHERE table_name = 'user_preferences') THEN
            RAISE EXCEPTION
                'user_preferences is not present in _tables even after '
                    '_p_update_tables(), so its audit columns cannot be added.';
        END IF;
    END
$$;

-- Adds created_at / updated_at with the set_updated_at trigger, then
-- id_created_by_user / id_updated_by_user with their foreign keys. Both are
-- idempotent across every flagged table.
CALL _p_update_tables_timestamps();
CALL _p_update_tables_user_ids();

-- migrate:down

