-- Something a story keeps track of: a person, a place, a thing, a piece of
-- ephemera, or anything else. Replaces characters, which held only people.
--
-- `kind` is NOT declared here. _p_update_tables_kinds() builds it, and the
-- elements_kind enum behind it, from the kind_values declared below. Its
-- status runs through the elements workflow seeded in
-- seeds/seed_s_statuses.sql (PENDING, READY and INACTIVE, each of which may
-- move to either of the others; PENDING is the default), and the workflow
-- procedures add the CHECK on status, the pending_at / ready_at / inactive_at
-- columns, the trigger that stamps them and the trigger that rejects any
-- transition the workflow does not list.
--
-- The storyteller who wrote the element is id_created_by_user, which the
-- metatable procedures add along with created_at / updated_at, so no user
-- column is declared here.
CREATE TABLE IF NOT EXISTS elements (
    id_element   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_story     integer NOT NULL REFERENCES stories (id_story) ON DELETE CASCADE,
    status       varchar NOT NULL DEFAULT 'PENDING',
    initial_name text,
    name         text    NOT NULL,
    title        text,
    description  text,
    notes        text
);

-- The whole _tables setup in one call: registration, the needs_* flags, the
-- audit columns and their foreign keys, activity_log, the tags column, the
-- kind column and its enum, the status workflow, and the foreign-key indexes.
-- It raises if the table is missing from _tables afterwards, or if workflow
-- -4 is unseeded.
CALL _p_set_and_update_table_features('elements',
    p_timestamps          := TRUE,
    p_user_ids            := TRUE,
    p_activity_log        := TRUE,
    p_tags                := TRUE,
    p_status_workflow_ids := ARRAY[-4],
    p_kind_values         := ARRAY['PERSON', 'PLACE', 'THING', 'OTHER', 'EPHEMERA']);

-- _p_update_tables_kinds() adds the column nullable, as it must for a table
-- that might already hold rows. Every element has a kind from the start.
ALTER TABLE elements ALTER COLUMN kind SET NOT NULL;
