-- Thumbs up / thumbs down feedback left from the menu bar's feedback popover,
-- one row per submission. The submitter is id_created_by_user, which the
-- metatable procedures below add along with created_at / updated_at, so no
-- user column is declared here. ip_address is nullable because local
-- development has no proxy in front of Next and therefore no x-forwarded-for
-- header to read.
CREATE TABLE IF NOT EXISTS feedback (
    id_feedback integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_positive boolean NOT NULL,
    page_path   text    NOT NULL,
    feedback    text,
    ip_address  text
);

-- Register the table so the needs_* flags have a row to land on. On a
-- database built from scratch _tables may be empty at this point.
CALL _p_update_tables();

-- _p_update_tables() only overwrites the has_* flags on conflict, never the
-- needs_* ones, so this survives later runs.
UPDATE _tables
SET needs_timestamps = TRUE,
    needs_user_ids   = TRUE,
    updated_at       = NOW()
WHERE table_name = 'feedback';

-- A table absent from _tables would silently miss out, so say so instead.
DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM _tables WHERE table_name = 'feedback') THEN
            RAISE EXCEPTION
                'feedback is not present in _tables even after '
                    '_p_update_tables(), so its audit columns cannot be added.';
        END IF;
    END
$$;

-- Adds created_at / updated_at with the set_updated_at trigger, then
-- id_created_by_user / id_updated_by_user with their foreign keys. Both are
-- idempotent across every flagged table.
CALL _p_update_tables_timestamps();
CALL _p_update_tables_user_ids();
