-- A picture (or later, any file) attached to a story, a session or a scene.
-- Replaces the image_url / image_link columns those tables used to carry: one
-- shape for every kind, several files per object, and -- because a row exists
-- before its bytes do -- an upload that has a state rather than being an
-- event that either happened or did not.
--
-- `kind` is NOT declared here. _p_update_tables_kinds() builds it, and the
-- attachments_kind enum behind it, from the kind_values declared below.
CREATE TABLE IF NOT EXISTS attachments (
    id_attachment integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Null until claimed: a create form uploads before its story, session or
    -- scene exists, and the create action claims the row when it is saved.
    external_id   integer,
    status        varchar NOT NULL DEFAULT 'UPLOADING',
    url           text,
    -- Recorded at write time rather than re-derived from the URL, so a change
    -- of Blob domain cannot silently turn our own files into other people's.
    is_uploaded   boolean NOT NULL DEFAULT FALSE,
    file_name     text,
    content_type  varchar,
    byte_size     bigint,
    sort_order    integer,
    -- What makes READY mean the address exists.
    CONSTRAINT attachments_ready_has_url CHECK (status <> 'READY' OR url IS NOT NULL)
);

-- The whole _tables setup in one call: registration, the needs_* flags, the
-- audit columns and their foreign keys, activity_log, the kind column and its
-- enum, the status workflow, and the foreign-key indexes. It raises if the
-- table is missing from _tables afterwards, or if workflow -3 is unseeded.
CALL _p_set_and_update_table_features('attachments',
    p_timestamps          := TRUE,
    p_user_ids            := TRUE,
    p_activity_log        := TRUE,
    p_status_workflow_ids := ARRAY[-3],
    p_kind_values         := ARRAY['STORY', 'STORY_SESSION', 'STORY_SCENE']);

-- _p_update_tables_kinds() adds the column nullable, as it must for a table
-- that might already hold rows. Every attachment has a kind from the start.
ALTER TABLE attachments ALTER COLUMN kind SET NOT NULL;

-- Written by hand because _p_update_fk_indexes only indexes real foreign
-- keys, and external_id is not one. Every read of this table is "the
-- attachments of this object".
CREATE INDEX IF NOT EXISTS attachments_kind_external_id_idx
    ON attachments (kind, external_id);
