-- Announcements for the home page's News section, one row each. A row is
-- shown from starts_at until expires_at; expires_at is NULL for an item that
-- never lapses. starts_at defaults to now so an item posted without a date
-- appears at once, and the CHECK stops an item from expiring before it starts.
--
-- The author is id_created_by_user, which the metatable procedures below add
-- along with created_at / updated_at, so no user column is declared here.
-- Archival (is_archived, archived_at, id_archived_by_user) comes the same
-- way, so an item can be taken down without deleting it.
CREATE TABLE IF NOT EXISTS news (
    id_news    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      text NOT NULL,
    body       text NOT NULL,
    starts_at  timestamp with time zone NOT NULL DEFAULT now(),
    expires_at timestamp with time zone,
    CONSTRAINT news_expires_after_starts CHECK (expires_at IS NULL OR expires_at > starts_at)
);

-- Register the table so the needs_* flags have a row to land on. On a
-- database built from scratch _tables may be empty at this point.
CALL _p_update_tables();

-- _p_update_tables() only overwrites the has_* flags on conflict, never the
-- needs_* ones, so this survives later runs.
UPDATE _tables
SET needs_timestamps = TRUE,
    needs_user_ids   = TRUE,
    needs_archival   = TRUE,
    updated_at       = NOW()
WHERE table_name = 'news';

-- A table absent from _tables would silently miss out, so say so instead.
DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM _tables WHERE table_name = 'news') THEN
            RAISE EXCEPTION
                'news is not present in _tables even after '
                    '_p_update_tables(), so its audit columns cannot be added.';
        END IF;
    END
$$;

-- Adds created_at / updated_at with the set_updated_at trigger, then
-- id_created_by_user / id_updated_by_user with their foreign keys, then
-- is_archived / archived_at / id_archived_by_user with the triggers that keep
-- archived_at and id_archived_by_user in step with is_archived. All three are
-- idempotent across every flagged table.
CALL _p_update_tables_timestamps();
CALL _p_update_tables_user_ids();
CALL _p_update_tables_archives();
