-- One sitting of a game: a row each time the table is opened for play. Its
-- status runs through the game_sessions workflow seeded in
-- seeds/seed_s_statuses.sql (open <-> suspended, either -> done; open is the
-- default), and the workflow procedures below add everything that enforces
-- it: the CHECK on status, the open_at / suspended_at / done_at columns, the
-- trigger that stamps each one when the row enters that status, and the
-- trigger that rejects any transition the workflow does not list. Every
-- transition is also appended to activity_log, which the transition trigger
-- expects to find on the table.
--
-- The storyteller who opened the session is id_created_by_user, which the
-- metatable procedures add along with created_at / updated_at, so no user
-- column is declared here.
CREATE TABLE IF NOT EXISTS game_sessions (
    id_game_session integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_game         integer NOT NULL REFERENCES games (id_game) ON DELETE CASCADE,
    status          varchar NOT NULL DEFAULT 'open'
);

-- Register the table so the needs_* flags have a row to land on. On a
-- database built from scratch _tables may be empty at this point.
CALL _p_update_tables();

-- _p_update_tables() only overwrites the has_* flags on conflict, never the
-- needs_* ones or the workflow mapping, so this survives later runs. -1 is
-- the Game Sessions Status Workflow in seeds/seed_s_status_workflows.sql.
UPDATE _tables
SET needs_timestamps      = TRUE,
    needs_user_ids        = TRUE,
    needs_activity_log    = TRUE,
    s_status_workflow_ids = ARRAY[-1],
    updated_at            = NOW()
WHERE table_name = 'game_sessions';

-- A table absent from _tables would silently miss out, and a workflow that
-- has not been seeded would leave status unguarded, so say so instead.
DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM _tables WHERE table_name = 'game_sessions') THEN
            RAISE EXCEPTION
                'game_sessions is not present in _tables even after '
                    '_p_update_tables(), so its audit columns cannot be added.';
        END IF;
        IF NOT EXISTS (SELECT 1 FROM s_status_workflows WHERE s_status_workflow_id = -1) THEN
            RAISE EXCEPTION
                'Workflow -1 is not present in s_status_workflows; run the '
                    'seed_s_status_workflows and seed_s_statuses migrations first.';
        END IF;
    END
$$;

-- Adds created_at / updated_at with the set_updated_at trigger, then
-- id_created_by_user / id_updated_by_user with their foreign keys, then
-- activity_log. All three are idempotent across every flagged table.
CALL _p_update_tables_timestamps();
CALL _p_update_tables_user_ids();
CALL _p_update_tables_activity_log();

-- Build the workflow onto the table: the CHECK constraint on status, the
-- open_at / suspended_at / done_at columns, the BEFORE INSERT OR UPDATE
-- trigger that stamps them, and the BEFORE UPDATE trigger that validates a
-- transition against s_statuses. _p_attach_workflow_triggers does nothing
-- while the workflow has no workflow_trigger, and is here so a later one is
-- picked up by a re-run.
CALL _p_update_workflow_constraints();
CALL _p_update_workflow_columns();
CALL _p_update_workflow_status_timestamp_triggers();
CALL _p_attach_workflow_triggers();
CALL _p_attach_status_transition_triggers();

-- How long the session ran, in whole minutes, from open_at to done_at. Both
-- columns are stamped by the workflow trigger, so this has to come after the
-- workflow is built. NULL until the session is done. open_at is re-stamped
-- each time a suspended session reopens, so a session that was suspended
-- measures from its last reopening, not its first.
ALTER TABLE game_sessions
    ADD COLUMN IF NOT EXISTS length integer
        GENERATED ALWAYS AS (round(EXTRACT(EPOCH FROM (done_at - open_at)) / 60)::integer) STORED;
