-- A user's favorite stories, for the "Favorite Stories" section of the Stories
-- page. One row per (story, user); the audit columns come from the metatable
-- procedures below rather than being declared here, so they match stories.
CREATE TABLE IF NOT EXISTS story_favorites (
    id_story_favorite integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_story          bigint NOT NULL REFERENCES stories (id_story) ON DELETE CASCADE,
    id_user          uuid   NOT NULL REFERENCES users (id_user) ON DELETE CASCADE,
    UNIQUE (id_story, id_user)
);

-- Register the table so the needs_* flags have a row to land on. On a
-- database built from scratch _tables may be empty at this point.
CALL _p_update_tables();

-- _p_update_tables() only overwrites the has_* flags on conflict, never the
-- needs_* ones, so this survives later runs.
UPDATE _tables
SET needs_timestamps = TRUE,
    needs_user_ids   = TRUE,
    updated_at       = NOW()
WHERE table_name = 'story_favorites';

-- A table absent from _tables would silently miss out, so say so instead.
DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM _tables WHERE table_name = 'story_favorites') THEN
            RAISE EXCEPTION
                'story_favorites is not present in _tables even after '
                    '_p_update_tables(), so its audit columns cannot be added.';
        END IF;
    END
$$;

-- Adds created_at / updated_at with the set_updated_at trigger, then
-- id_created_by_user / id_updated_by_user with their foreign keys. Both are
-- idempotent across every flagged table.
CALL _p_update_tables_timestamps();
CALL _p_update_tables_user_ids();

